### ISSUE TITLE
Amount of orange peel before bottling underspecified

### ISSUE THREAD

**Issue by nederdirk** [wearespindle/beer-recipes#2]
While preparing to brew this beer on a 1/10 scale on my home brewing installation, I noticed that the orange peel addition before bottling was not entirely clear. How much orange peel should I add to the carboy before bottling the 503? Also: should I use sweet or bitter orange peel?

Cheers 🍻

**Comment by m-vellinga** [comment]
@hbokh Could you answer this question?

**Comment by hbokh** [comment]
Hi @nederdirk - you can use the same amount of orange peel as the lemon peel.  
Our "503" had the bitter orange peel as far as I can recall (you know, Korsakovs...), but if you like your beers less IPA-ish, you might consider using the sweet one instead. But take care: you might end up with a Radler instead!

Enjoy you brew, with mates. Cheers!
